version: '3.8'
      

networks:
  backend:

volumes:
  db_data:

services:
  db:
    image: postgres:14.1-alpine
    hostname: pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokebase
    ports:
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./data:/tmp/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - backend

  
  
  api:
    hostname: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend_homework/api/.secret.env
      - backend_homework/api/.database.env
    command:   "sh -c 'alembic upgrade head && ./start'"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend
  

  populate_db:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend_homework/api/.secret.env
      - backend_homework/api/.database.env
    command:   "sh -c 'python populate_db.py '"
    depends_on:
      - db
      - api
    networks:
      - backend



      